# $FreeBSD$

PORTNAME=	gtable
PORTVERSION=	0.2.0
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Arrange grobs in tables

LICENSE=	GPLv2

USES=	r-library

.include <bsd.port.mk>
