# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	DT
PORTVERSION=	0.1
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Wrapper of the JavaScript Library 'DataTables'

LICENSE=	GPLv3

RUN_DEPENDS=	R-htmltools>0:${PORTSDIR}/textproc/R-htmltools \
		R-htmlwidgets>=0.4:${PORTSDIR}/www/R-htmlwidgets \
		R-magrittr>0:${PORTSDIR}/devel/R-magrittr

USES=	r-packages

.include <bsd.port.mk>
