# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	scrapeR
PORTVERSION=	0.1.6
PORTREVISION=	13
CATEGORIES=	www
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for Scraping Data from HTML and XML Documents

RUN_DEPENDS=	R-XML>0:${PORTSDIR}/textproc/R-XML \
		R-RCurl>0:${PORTSDIR}/ftp/R-RCurl

USES=	r-packages:auto-plist

.include <bsd.port.mk>
