# $FreeBSD$

PORTNAME=	Hmisc
DISTVERSION=	3.10-1
PORTREVISION=	7
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Harrell Miscellaneous functions useful for data analysis

LICENSE=	GPLv2

USES=	r-packages

.include <bsd.port.mk>
