# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	visNetwork
PORTVERSION=	0.2.1
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Network Visualization using 'vis.js' Library

LICENSE=	MIT

RUN_DEPENDS=	R-htmlwidgets>0:${PORTSDIR}/www/R-htmlwidgets \
		R-htmltools>0:${PORTSDIR}/textproc/R-htmltools \
		R-jsonlite>0:${PORTSDIR}/converters/R-jsonlite \
		R-magrittr>0:${PORTSDIR}/devel/R-magrittr

USES=	r-packages

.include <bsd.port.mk>
