# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	RColorBrewer
DISTVERSION=	1.1-2
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	ColorBrewer palettes

LICENSE=	APACHE20

USES=	r-packages:auto-plist

.include <bsd.port.mk>
