# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	portfolio
DISTVERSION=	0.4-7
CATEGORIES=	finance
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Analysing equity portfolios

LICENSE=	GPLv2+

USES=	cran:auto-plist

.include <bsd.port.mk>
