# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	markdown
PORTVERSION=	0.7.7
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Markdown Rendering for R

LICENSE=	GPLv2

RUN_DEPENDS=	R-cran-mime>=0.3:${PORTSDIR}/misc/R-cran-mime

USES=	r-packages

.include <bsd.port.mk>
