PORTNAME=	resp
DISTVERSIONPREFIX=	v
DISTVERSION=	1.0
CATEGORIES=	science python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Restrained Electrostatic Potential
WWW=		https://github.com/cdsgroup/resp

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

RUN_DEPENDS=	psi4>0:science/psi4

USES=		python
USE_PYTHON=	autoplist distutils

USE_GITHUB=	yes
GH_ACCOUNT=	cdsgroup

.include <bsd.port.mk>
