# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	RFinanceYJ
PORTVERSION=	0.3.1
PORTREVISION=	6
CATEGORIES=	finance
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Japanese stock market from Yahoo!-finance-Japan

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	R-XML>0:${PORTSDIR}/textproc/R-XML \
		R-xts>0:${PORTSDIR}/math/R-xts

USES=	r-packages:auto-plist

.include <bsd.port.mk>
