# $FreeBSD$

PORTNAME=	gbm
DISTVERSION=	2.0-8
PORTREVISION=	6
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Extensions to AdaBoost algorithm

LICENSE=	GPLv2

USES=	r-packages

.include <bsd.port.mk>
