# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	R6
PORTVERSION=	2.1.2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Classes with reference semantics

LICENSE=	MIT

USES=	r-library

.include <bsd.port.mk>
