# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	bitops
DISTVERSION=	1.0-6
PORTREVISION=	4
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Functions for Bitwise operations

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=	r-packages

.include <bsd.port.mk>
