# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	Epi
PORTVERSION=	2.0
CATEGORIES=	science
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Package for statistical analysis in epidemiology

LICENSE=	GPLv2

RUN_DEPENDS=	R-cmprsk>0:${PORTSDIR}/science/R-cmprsk \
		R-etm>0:${PORTSDIR}/science/R-etm \
		R-plyr>0:${PORTSDIR}/devel/R-plyr

USES=	r-packages

.include <bsd.port.mk>
