# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD$

PORTNAME=	assertthat
DISTVERSION=	0.1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Easy pre and post assertions

LICENSE=	GPLv3

USES=	r-packages:auto-plist

.include <bsd.port.mk>
