# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	bdsmatrix
DISTVERSION=	1.3-2
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Routines for Block Diagonal Symmetric matrices

LICENSE=	LGPL20

USES=	r-packages:auto-plist

.include <bsd.port.mk>
