# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	colorspace
DISTVERSION=	1.2-6
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Color Space Manipulation

LICENSE=	BSD3CLAUSE

USES=	r-packages

.include <bsd.port.mk>
