# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	ROAuth
PORTVERSION=	0.9.6
CATEGORIES=	security
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	R interface for OAuth

LICENSE=	ART20

RUN_DEPENDS=	R-RCurl>0:${PORTSDIR}/ftp/R-RCurl \
		R-digest>0:${PORTSDIR}/security/R-digest

USES=	r-packages:auto-plist

.include <bsd.port.mk>
