# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	whisker
DISTVERSION=	0.3-2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Whisker is a {{Mustache}} implementation in R

LICENSE=	GPLv3

USES=	cran:auto-plist

.include <bsd.port.mk>
