# Created by: Akinori MUSHA aka knu <knu@idaemons.org>
# $FreeBSD$

PORTNAME=	locale
PORTVERSION=	2.0.8
CATEGORIES=	devel rubygems
MASTER_SITES=	RG
PKGNAMESUFFIX=	208

MAINTAINER=	knu@FreeBSD.org
COMMENT=	Pure ruby library to support locales

LICENSE=	RUBY LGPL3
LICENSE_COMB=	dual

USE_RUBY=	yes
USE_RUBYGEMS=	yes
RUBYGEM_AUTOPLIST=	yes

PORTSCOUT=	ignore:1

.include <bsd.port.mk>
