# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD$

PORTNAME=	gsubfn
DISTVERSION=	0.6-5
PORTREVISION=	6
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R package used for string matching, substitution and parsing

LICENSE=	GPLv2

RUN_DEPENDS=	R-proto>=0.3.9.2_6:${PORTSDIR}/devel/R-proto

USES=	r-packages:auto-plist

.include <bsd.port.mk>
