# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	TTR
DISTVERSION=	0.23-1
CATEGORIES=	finance
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Technical Trading Rules

LICENSE=	GPLv2

RUN_DEPENDS=	R-xts>=0.9.3:${PORTSDIR}/math/R-xts

USES=	r-packages

.include <bsd.port.mk>
