# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	quantreg
PORTVERSION=	5.21
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Quantile Regression

LICENSE=	GPLv2+

RUN_DEPENDS=	R-SparseM>0:${PORTSDIR}/math/R-SparseM \
		R-MatrixModels>0:${PORTSDIR}/math/R-MatrixModels

USES=	r-packages:auto-plist

.include <bsd.port.mk>
