# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	PerformanceAnalytics
PORTVERSION=	1.4.3541
CATEGORIES=	finance
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Econometric tools for performance and risk analysis

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-zoo>0:${PORTSDIR}/math/R-zoo \
		R-xts>=0.9:${PORTSDIR}/math/R-xts

USES=	r-packages

.include <bsd.port.mk>
