# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	BH
DISTVERSION=	1.60.0-1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Boost C++ Header Files

LICENSE=	BSL

USES=	r-packages

.include <bsd.port.mk>
