# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	htmltools
PORTVERSION=	0.3.5
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools for HTML generation and output

LICENSE=	GPLv2+

RUN_DEPENDS=	R-digest>0:${PORTSDIR}/security/R-digest \
		R-Rcpp>0:${PORTSDIR}/devel/R-Rcpp

USES=	r-packages:auto-plist

.include <bsd.port.mk>
