# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	evaluate
PORTVERSION=	0.8.3
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Parsing and Evaluation Tools

LICENSE=	MIT

RUN_DEPENDS=	R-stringr>=0.6.2:${PORTSDIR}/textproc/R-stringr

USES=	r-packages

.include <bsd.port.mk>
