# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD$

PORTNAME=	RUnit
PORTVERSION=	0.4.28
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	R functions implementing a Unit Testing framework

LICENSE=	GPLv2

USES=	r-library

.include <bsd.port.mk>
