# $FreeBSD$

PORTNAME=	askpass
PORTVERSION=	1.1
CATEGORIES=	security
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Safe Password Entry for R, Git, and SSH

LICENSE=	MIT

USES=		cran:auto-plist,compiles

.include <bsd.port.mk>
