# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	sandwich
DISTVERSION=	2.3-4
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Robust Covariance Matrix Estimators

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-zoo>0:${PORTSDIR}/math/R-zoo

USES=	r-packages

.include <bsd.port.mk>
