# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	strucchange
DISTVERSION=	1.5-1
CATEGORIES=	finance
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Testing, Monitoring, and Dating Structural Changes

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-zoo>0:${PORTSDIR}/math/R-zoo \
		R-sandwich>0:${PORTSDIR}/math/R-sandwich

USES=	r-packages:auto-plist

.include <bsd.port.mk>
