# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	git2r
PORTVERSION=	0.11.0
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Provides Access to Git Repositories

LICENSE=	GPLv2

USES=	cran:auto-plist

.include <bsd.port.mk>
