# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	caTools
PORTVERSION=	1.17.1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Tools: moving window statistics, GIF, Base64, ROC AUC, etc

LICENSE=	GPLv3

RUN_DEPENDS=	R-bitops>0:${PORTSDIR}/devel/R-bitops

USES=	r-packages

.include <bsd.port.mk>
