# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	dichromat
DISTVERSION=	2.0-0
PORTREVISION=	6
CATEGORIES=	graphics
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Color schemes for dichromats

LICENSE=	GPLv2

USES=	r-library

.include <bsd.port.mk>
