# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	tseriesChaos
DISTVERSION=	0.1-13
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Analysis of nonlinear time series

LICENSE=	GPLv2

RUN_DEPENDS=	R-cran-deSolve>0:${PORTSDIR}/math/R-cran-deSolve

USES=	cran:auto-plist

.include <bsd.port.mk>
