# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	quantmod
DISTVERSION=	0.4-5
CATEGORIES=	finance
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Quantitative Financial Modelling and Trading Framework for R

LICENSE=	GPLv3

RUN_DEPENDS=	R-xts>=0.9.0:${PORTSDIR}/math/R-xts \
		R-zoo>0:${PORTSDIR}/math/R-zoo \
		R-TTR>=0.2:${PORTSDIR}/finance/R-TTR

USES=	r-packages

.include <bsd.port.mk>
