# Created by: Wen Heping <wen@FreeBSD.org>
# $FreeBSD$

PORTNAME=	geepack
DISTVERSION=	1.2-0.1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Generalized Estimating Equation Package

LICENSE=	GPLv3

USES=		r-packages:auto-plist

.include <bsd.port.mk>
