# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	xtable
DISTVERSION=	1.8-2
CATEGORIES=	textproc
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Export tables to LaTeX or HTML

LICENSE=	GPLv2+

USES=	r-packages

.include <bsd.port.mk>
