# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD$

PORTNAME=	car
DISTVERSION=	2.1-1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	Companion to Applied Regression for R

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-pbkrtest>=0.3.2:${PORTSDIR}/math/R-pbkrtest \
		R-quantreg>0:${PORTSDIR}/math/R-quantreg

USES=	r-packages

.include <bsd.port.mk>
