# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	RSNNS
DISTVERSION=	0.4-6
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	R wrapping for the Stuttgart Neural Network Simulator

LICENSE=	LGPL20 LGPL21 LGPL3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-cran-Rcpp>=0.8.5:${PORTSDIR}/devel/R-cran-Rcpp

USES=	cran:auto-plist

.include <bsd.port.mk>
