# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	rngtools
PORTVERSION=	1.2.4
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Utility functions for working with Random Number Generators

LICENSE=	GPLv3

RUN_DEPENDS=	R-pkgmaker>=0.20:${PORTSDIR}/devel/R-pkgmaker

USES=	r-packages

.include <bsd.port.mk>
