# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	labeling
PORTVERSION=	0.3
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Provides a range of axis labeling algorithms

LICENSE=	MIT

USES=	r-packages

.include <bsd.port.mk>
