# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	rversions
PORTVERSION=	1.0.2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Query 'R' Versions, Including 'r-release' and 'r-oldrel'

LICENSE=	MIT

RUN_DEPENDS=	R-cran-curl>0:${PORTSDIR}/ftp/R-cran-curl \
		R-cran-xml2>0:${PORTSDIR}/textproc/R-cran-xml2

USES=	cran:auto-plist

.include <bsd.port.mk>
