# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	registry
PORTVERSION=	0.3
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Registry infrastructure

LICENSE=	GPLv2

USES=	r-packages

.include <bsd.port.mk>
