# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	selectr
DISTVERSION=	0.2-3
CATEGORIES=	www
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Translate CSS Selectors to XPath Expressions

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	R-XML>0:${PORTSDIR}/textproc/R-XML \
		R-stringr>0:${PORTSDIR}/textproc/R-stringr

USES=	r-packages

.include <bsd.port.mk>
