# $FreeBSD$

PORTNAME=	randomForest
DISTVERSION=	4.6-7
PORTREVISION=	6
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Classification based on a forest of trees using random inputs

RUN_DEPENDS=	R-RColorBrewer>=1.0.5_6:${PORTSDIR}/graphics/R-RColorBrewer

USES=	r-packages

.include <bsd.port.mk>
