# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	doParallel
PORTVERSION=	1.0.10
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Foreach parallel adaptor for the parallel package

LICENSE=	GPLv2

RUN_DEPENDS=	R-foreach>=1.2.0:${PORTSDIR}/devel/R-foreach \
		R-iterators>=1.0.0:${PORTSDIR}/devel/R-iterators

USES=	r-packages

.include <bsd.port.mk>
