# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD$

PORTNAME=	Zelig
DISTVERSION=	5.0-11
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	Everyone's Statistical Software

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

BUILD_DEPENDS=	R-AER>=0:${PORTSDIR}/finance/R-AER \
		R-Amelia>=0:${PORTSDIR}/math/R-Amelia \
		R-sandwich>=0:${PORTSDIR}/math/R-sandwich \
		R-VGAM>=0:${PORTSDIR}/math/R-VGAM \
		R-plyr>=0:${PORTSDIR}/devel/R-plyr \
		R-quantreg>=0:${PORTSDIR}/math/R-quantreg \
		R-MCMCpack>=0:${PORTSDIR}/math/R-MCMCpack \
		R-maxLik>=0:${PORTSDIR}/math/R-maxLik \
		R-jsonlite>=0:${PORTSDIR}/converters/R-jsonlite \
		R-dplyr>=0:${PORTSDIR}/math/R-dplyr \
		R-MatchIt>=0:${PORTSDIR}/math/R-MatchIt \
		R-geepack>=0:${PORTSDIR}/math/R-geepack \
		R-survey>=0:${PORTSDIR}/math/R-survey
RUN_DEPENDS=	R-AER>=0:${PORTSDIR}/finance/R-AER \
		R-Amelia>=0:${PORTSDIR}/math/R-Amelia \
		R-sandwich>=0:${PORTSDIR}/math/R-sandwich \
		R-VGAM>=0:${PORTSDIR}/math/R-VGAM \
		R-plyr>=0:${PORTSDIR}/devel/R-plyr \
		R-quantreg>=0:${PORTSDIR}/math/R-quantreg \
		R-MCMCpack>=0:${PORTSDIR}/math/R-MCMCpack \
		R-maxLik>=0:${PORTSDIR}/math/R-maxLik \
		R-jsonlite>=0:${PORTSDIR}/converters/R-jsonlite \
		R-dplyr>=0:${PORTSDIR}/math/R-dplyr \
		R-MatchIt>=0:${PORTSDIR}/math/R-MatchIt \
		R-geepack>=0:${PORTSDIR}/math/R-geepack \
		R-survey>=0:${PORTSDIR}/math/R-survey

USES=	r-packages

.include <bsd.port.mk>
