# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD$

PORTNAME=	microbenchmark
DISTVERSION=	1.4-2
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Infrastructure to measure the execution time of R expressions

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	R-ggplot2>0:${PORTSDIR}/graphics/R-ggplot2

USES=	r-packages:auto-plist

.include <bsd.port.mk>
