# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	KFAS
PORTVERSION=	1.2.2
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Kalman filter and smoothers for exponential family state space models

LICENSE=	GPLv2+

USES=	r-packages

.include <bsd.port.mk>
