# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	reshape
PORTVERSION=	0.8.5
PORTREVISION=	1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	R package for flexibly restructuring and aggregating data

LICENSE=	MIT

RUN_DEPENDS=	R-plyr>0:${PORTSDIR}/devel/R-plyr

USES=	r-packages

.include <bsd.port.mk>
