# Created by: Steven Kreuzer <skreuzer@FreeBSD.org>
# $FreeBSD$

PORTNAME=	RSQLite
PORTVERSION=	1.0.0
CATEGORIES=	databases
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	skreuzer@FreeBSD.org
COMMENT=	Database Interface R driver for SQLite

LICENSE=	LGPL20

BUILD_DEPENDS=	R-DBI>=0.2.5:${PORTSDIR}/databases/R-DBI
RUN_DEPENDS=	R-DBI>=0.2.5:${PORTSDIR}/databases/R-DBI

USES=	r-packages

.include <bsd.port.mk>
