# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	foreach
PORTVERSION=	1.4.3
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Foreach looping construct for R

LICENSE=	APACHE20

RUN_DEPENDS=	R-iterators>=1.0.0:${PORTSDIR}/devel/R-iterators

USES=	r-packages:auto-plist

.include <bsd.port.mk>
