# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	itertools
DISTVERSION=	0.1-3
PORTREVISION=	1
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Iterator Tools for R

LICENSE=	GPLv2

RUN_DEPENDS=	R-iterators>=1.0.0:${PORTSDIR}/devel/R-iterators

USES=	r-packages

.include <bsd.port.mk>
