# Created by: David Naylor <naylor.b.david@gmail.com>
# $FreeBSD$

PORTNAME=	RSvgDevice
PORTVERSION=	0.6.4.4
PORTREVISION=	1
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	dbn@FreeBSD.org
COMMENT=	R SVG graphics device

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=	r-packages

.include <bsd.port.mk>
