# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	RgoogleMaps
PORTVERSION=	1.2.0.7
CATEGORIES=	www
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Overlays on Google map tiles in R

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

RUN_DEPENDS=	R-png>0:${PORTSDIR}/graphics/R-png \
		R-RJSONIO>0:${PORTSDIR}/converters/R-RJSONIO

USES=	r-packages:auto-plist

.include <bsd.port.mk>
