# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	minqa
PORTVERSION=	1.2.4
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Derivative-free optimization algorithms by quadratic approximation

LICENSE=	GPLv2

RUN_DEPENDS=	R-Rcpp>=0.9.10:${PORTSDIR}/devel/R-Rcpp

USES=	r-packages

.include <bsd.port.mk>
