# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	rjson
PORTVERSION=	0.2.15
CATEGORIES=	converters
DISTNAME=	${PORTNAME}_${PORTVERSION}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	JSON for R

LICENSE=	GPLv2

USES=	r-packages:auto-plist

.include <bsd.port.mk>
