# Created by: Wen Heping <wenheping@gmail.com>
# $FreeBSD$

PORTNAME=	gpclib
DISTVERSION=	1.5-5
PORTREVISION=	5
CATEGORIES=	math
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	wen@FreeBSD.org
COMMENT=	General Polygon Clipping Library for R

USES=	r-library

.include <bsd.port.mk>
