# Created by: TAKATSU Tomonari <tota@FreeBSD.org>
# $FreeBSD$

PORTNAME=	purplex
PORTVERSION=	0.2.4
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	tota@FreeBSD.org
COMMENT=	Pure Python lexer and parser implementation

LICENSE=	MIT

USES=		python:2.7+
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
