# Created by: Jukka A. Ukkonen <jau@iki.fi>
# $FreeBSD:$

PORTNAME=	Rmpfr
DISTVERSION=	0.6-0
#PORTREVISION=
CATEGORIES=	devel
DISTNAME=	${PORTNAME}_${DISTVERSION}

MAINTAINER=	jau@iki.fi
COMMENT=	An R wrapper for the mpfr multiple precision library

LIB_DEPENDS=	libgmp.so:math/gmp \
		libmpfr.so:math/mpfr

LICENSE=	GPLv2 GPLv3
LICENSE_COMB=	dual

USES=	cran:auto-plist

.include <bsd.port.mk>
